"""Canonical niches and copyright-safe short-form pattern library."""

from __future__ import annotations

from typing import Any

ALL_PLATFORMS = ("youtube_shorts", "instagram_reels", "tiktok")
DO_NOT_COPY_WARNING = (
    "Use this structural pattern only; do not copy a creator's wording, script, "
    "caption, title, thumbnail, or distinctive creative expression."
)

SUPPORTED_NICHES: tuple[str, ...] = (
    "podcast_interview",
    "motivational",
    "business_money",
    "self_improvement",
    "education_tutorial",
    "entertainment_comedy",
    "gaming_stream",
    "reaction",
    "music_singing",
    "sports",
    "emotional_story",
    "news_commentary",
    "debate_argument",
    "fitness",
    "relationship_life_advice",
    "tech_ai",
    "unknown_mixed",
)

NICHE_ALIASES: dict[str, str] = {
    "auto": "unknown_mixed",
    "business": "business_money",
    "creator_education": "education_tutorial",
    "education": "education_tutorial",
    "educational": "education_tutorial",
    "entertainment": "entertainment_comedy",
    "funny": "entertainment_comedy",
    "gaming": "gaming_stream",
    "gaming_streaming": "gaming_stream",
    "interview": "podcast_interview",
    "motivation": "motivational",
    "music": "music_singing",
    "podcast": "podcast_interview",
    "productivity": "self_improvement",
    "relationship": "relationship_life_advice",
    "stream": "gaming_stream",
    "technology": "tech_ai",
    "unknown": "unknown_mixed",
}

NICHE_KEYWORDS: dict[str, tuple[str, ...]] = {
    "podcast_interview": (
        "podcast",
        "interview",
        "guest",
        "host",
        "conversation",
        "what happened",
        "my question",
    ),
    "motivational": (
        "discipline",
        "success",
        "failure",
        "mindset",
        "purpose",
        "motivation",
        "never give up",
        "dream",
    ),
    "business_money": (
        "business",
        "money",
        "revenue",
        "profit",
        "customer",
        "sales",
        "marketing",
        "investing",
        "startup",
        "income",
    ),
    "self_improvement": (
        "habit",
        "productivity",
        "focus",
        "routine",
        "time blocking",
        "self improvement",
        "confidence",
        "goals",
    ),
    "education_tutorial": (
        "tutorial",
        "how to",
        "learn",
        "lesson",
        "explain",
        "example",
        "step by step",
        "because",
        "study",
    ),
    "entertainment_comedy": (
        "funny",
        "joke",
        "comedy",
        "punchline",
        "laugh",
        "hilarious",
        "sketch",
    ),
    "gaming_stream": (
        "gaming",
        "gameplay",
        "stream",
        "chat",
        "level",
        "boss fight",
        "clutch",
        "no way",
    ),
    "reaction": (
        "reaction",
        "reacting",
        "i can't believe",
        "look at this",
        "watch this",
        "my response",
    ),
    "music_singing": (
        "sing",
        "singing",
        "song",
        "cover",
        "vocal",
        "chorus",
        "melody",
        "high note",
        "lyrics",
    ),
    "sports": (
        "match",
        "goal",
        "score",
        "player",
        "coach",
        "season",
        "football",
        "cricket",
        "basketball",
        "training camp",
    ),
    "emotional_story": (
        "i felt",
        "heartbroken",
        "grief",
        "changed my life",
        "emotional",
        "journey",
        "overcame",
        "tears",
    ),
    "news_commentary": (
        "breaking news",
        "report",
        "headline",
        "according to",
        "election",
        "policy",
        "today's news",
        "analysis",
    ),
    "debate_argument": (
        "debate",
        "argument",
        "disagree",
        "you're wrong",
        "counterpoint",
        "my position",
        "the evidence",
    ),
    "fitness": (
        "workout",
        "fitness",
        "exercise",
        "gym",
        "muscle",
        "training",
        "nutrition",
        "calories",
        "reps",
    ),
    "relationship_life_advice": (
        "relationship",
        "dating",
        "partner",
        "marriage",
        "breakup",
        "life advice",
        "boundaries",
        "communication",
    ),
    "tech_ai": (
        "artificial intelligence",
        "machine learning",
        "software",
        "coding",
        "developer",
        "technology",
        "chatgpt",
        "automation",
        "algorithm",
    ),
    "unknown_mixed": (),
}


def normalize_niche(value: str | None) -> str:
    """Return a supported canonical niche name."""

    raw = (value or "").strip().lower().replace("-", "_").replace(" ", "_")
    mapped = NICHE_ALIASES.get(raw, raw)
    return mapped if mapped in SUPPORTED_NICHES else "unknown_mixed"


def _pattern(
    pattern_id: str,
    category: str,
    label: str,
    description: str,
    example_structure: str,
    *,
    cues: tuple[str, ...],
    niches: tuple[str, ...] = (),
    platforms: tuple[str, ...] = ALL_PLATFORMS,
    confidence: float = 0.66,
    safety_notes: str = "Keep every claim faithful to the source material.",
) -> dict[str, Any]:
    return {
        "pattern_id": pattern_id,
        "id": pattern_id,
        "category": category,
        "label": label,
        "description": description,
        "applies_to_niches": list(niches or SUPPORTED_NICHES),
        "platforms": list(platforms),
        "evidence_source_ids": [],
        "confidence": confidence,
        "recency_score": 0.45,
        "safety_notes": safety_notes,
        "example_structure": example_structure,
        "do_not_copy_warning": DO_NOT_COPY_WARNING,
        "match_cues": list(cues),
        "cues": list(cues),
    }


_PATTERNS = (
    _pattern(
        "question_hook",
        "hook",
        "Question hook",
        "Open with a specific question the clip genuinely answers.",
        "Question -> brief context -> answer",
        cues=("why", "how", "what if", "have you ever"),
    ),
    _pattern(
        "curiosity_gap",
        "hook",
        "Curiosity gap",
        "Open one clear information gap and close it inside the clip.",
        "Unexpected premise -> withheld reason -> reveal",
        cues=("the reason", "what happened", "turns out", "nobody tells you"),
    ),
    _pattern(
        "payoff_first",
        "hook",
        "Payoff-first opening",
        "Lead with the result before briefly explaining how it happened.",
        "Result -> obstacle -> concise explanation",
        cues=("this changed", "the result", "finally", "here's what worked"),
    ),
    _pattern(
        "contrarian_truth",
        "hook",
        "Contrarian truth",
        "Challenge a familiar belief only when the clip supplies support.",
        "Common belief -> supported disagreement -> takeaway",
        cues=("most people are wrong", "the truth is", "actually", "i disagree"),
    ),
    _pattern(
        "mistake_warning",
        "hook",
        "Mistake warning",
        "Name a concrete mistake and resolve it with a useful correction.",
        "Mistake -> consequence -> correction",
        cues=("biggest mistake", "stop doing", "avoid this", "doing this wrong"),
    ),
    _pattern(
        "identity_hook",
        "hook",
        "Identity hook",
        "Address a relevant viewer identity without manipulating insecurity.",
        "Identity -> recognizable struggle -> earned lesson",
        cues=("if you're", "for anyone who", "people like us", "you are the kind"),
    ),
    _pattern(
        "high_stakes_hook",
        "hook",
        "High-stakes hook",
        "State a real consequence early without exaggerating risk or certainty.",
        "Supported consequence -> evidence -> measured conclusion",
        cues=("at stake", "could cost", "the risk", "matters because"),
        niches=("business_money", "news_commentary", "debate_argument", "fitness"),
    ),
    _pattern(
        "emotional_confession",
        "hook",
        "Emotional confession",
        "Use a truthful personal admission to establish immediate stakes.",
        "Admission -> consequence -> meaning",
        cues=("i was afraid", "i failed", "i never told", "honestly"),
    ),
    _pattern(
        "immediate_reaction",
        "hook",
        "Immediate reaction",
        "Start on the authentic reaction, then supply only needed context.",
        "Reaction -> quick context -> payoff",
        cues=("no way", "what just happened", "look at this", "i can't believe"),
        niches=("gaming_stream", "reaction", "sports", "entertainment_comedy"),
    ),
    _pattern(
        "before_after_hook",
        "hook",
        "Before-after hook",
        "Contrast a real starting state with an evidenced outcome.",
        "Before -> turning point -> after",
        cues=("before", "after", "used to", "now i"),
    ),
    _pattern(
        "problem_solution",
        "storytelling",
        "Problem to solution",
        "Define one problem, explain the key cause, and land on a usable solution.",
        "Problem -> cause -> solution",
        cues=("problem", "because", "solution", "fixed"),
    ),
    _pattern(
        "mistake_lesson",
        "storytelling",
        "Mistake to lesson",
        "Turn a concrete error into a clear lesson rather than a generic warning.",
        "Mistake -> consequence -> lesson",
        cues=("mistake", "learned", "should have", "never again"),
    ),
    _pattern(
        "pain_transformation",
        "storytelling",
        "Pain to transformation",
        "Move from a real struggle through a credible turning point to change.",
        "Struggle -> turning point -> changed behavior",
        cues=("struggled", "pain", "then i realized", "changed my life"),
        niches=("motivational", "self_improvement", "fitness", "emotional_story"),
    ),
    _pattern(
        "question_answer",
        "storytelling",
        "Question to answer",
        "Keep context short and resolve the opening question directly.",
        "Question -> evidence -> answer",
        cues=("why", "how", "answer", "that's why"),
    ),
    _pattern(
        "buildup_payoff",
        "storytelling",
        "Buildup to payoff",
        "Escalate only relevant beats before the satisfying result.",
        "Setup -> escalation -> payoff",
        cues=("then", "suddenly", "finally", "and that's when"),
    ),
    _pattern(
        "conflict_resolution",
        "storytelling",
        "Conflict to resolution",
        "Present the disagreement fairly and end with a supported resolution.",
        "Position -> tension -> resolution",
        cues=("disagree", "argument", "but", "we agreed"),
        niches=("podcast_interview", "debate_argument", "news_commentary"),
    ),
    _pattern(
        "confession_meaning",
        "storytelling",
        "Confession to meaning",
        "Connect a personal admission to an earned insight.",
        "Confession -> consequence -> meaning",
        cues=("i admit", "i felt", "i realized", "what it taught me"),
        niches=("podcast_interview", "emotional_story", "relationship_life_advice"),
    ),
    _pattern(
        "reaction_explanation",
        "storytelling",
        "Reaction to explanation",
        "Follow an authentic reaction with the concise reason it matters.",
        "Reaction -> evidence -> explanation",
        cues=("reaction", "because", "here's why", "what happened"),
        niches=("reaction", "gaming_stream", "sports", "news_commentary"),
    ),
    _pattern(
        "fast_setup_punchline",
        "storytelling",
        "Fast setup to punchline",
        "Keep only the setup needed for the joke or comic reversal.",
        "Lean setup -> escalation -> punchline",
        cues=("so i", "and then", "guess what", "punchline"),
        niches=("entertainment_comedy",),
    ),
    _pattern(
        "fast_first_sentence",
        "retention",
        "Fast first sentence",
        "Reach the first meaningful claim quickly and remove unsupported dead air.",
        "Meaningful first line within the opening seconds",
        cues=("why", "how", "the problem", "here's", "i learned"),
    ),
    _pattern(
        "open_loop",
        "retention",
        "Single open loop",
        "Create one clear viewer question and resolve it without stacking teases.",
        "Question -> rising evidence -> closure",
        cues=("but", "until", "what happened next", "the reason"),
    ),
    _pattern(
        "quick_context",
        "retention",
        "Quick context",
        "Supply only the names or premise needed to understand the moment.",
        "Hook -> one context line -> core beat",
        cues=("here's the context", "for context", "because", "at the time"),
    ),
    _pattern(
        "escalating_curiosity",
        "retention",
        "Escalating curiosity",
        "Let each beat add information or stakes before the reveal.",
        "Question -> stronger clue -> answer",
        cues=("then", "but", "even worse", "finally"),
    ),
    _pattern(
        "replay_worthy_moment",
        "retention",
        "Replay-worthy moment",
        "Center one dense reveal, reaction, skill moment, or punchline worth revisiting.",
        "Build -> compact peak -> clean tail",
        cues=("watch", "listen", "moment", "did you see"),
    ),
    _pattern(
        "practical_takeaway",
        "ending",
        "Practical takeaway",
        "End on the usable lesson rather than a trailing setup line.",
        "Evidence -> concise action or lesson",
        cues=("the lesson", "what i learned", "do this", "that's why"),
    ),
    _pattern(
        "twist_reveal",
        "ending",
        "Twist or reveal",
        "Land a supported reversal that resolves the clip's main question.",
        "Expectation -> evidence -> supported reversal",
        cues=("turns out", "actually", "the reveal", "but it was"),
    ),
    _pattern(
        "emotional_landing",
        "ending",
        "Emotional landing",
        "Give the emotional turn enough room to resolve without melodrama.",
        "Turn -> reflection -> final meaning",
        cues=("i felt", "it meant", "i realized", "from that day"),
    ),
    _pattern(
        "strong_quote",
        "ending",
        "Strong final line",
        "Hold on a concise source-faithful line that completes the thought.",
        "Story beat -> distilled final sentence",
        cues=("what matters", "remember", "the truth", "the lesson"),
    ),
    _pattern(
        "punchline",
        "ending",
        "Punchline ending",
        "Cut after the comic payoff, preserving enough reaction tail to land it.",
        "Setup -> reversal -> reaction tail",
        cues=("joke", "laugh", "and that's", "guess"),
        niches=("entertainment_comedy", "gaming_stream", "reaction"),
    ),
    _pattern(
        "satisfying_answer",
        "ending",
        "Satisfying answer",
        "Answer the opening question before the clip ends.",
        "Question -> proof -> direct answer",
        cues=("because", "the answer", "that's why", "so the reason"),
    ),
    _pattern(
        "bold_keywords",
        "caption",
        "Bold keyword emphasis",
        "Highlight a few meaningful hook and payoff words while keeping captions readable.",
        "Short phrase with one emphasized keyword",
        cues=("keyword", "caption", "emphasis"),
    ),
    _pattern(
        "short_high_contrast",
        "caption",
        "Short high-contrast captions",
        "Use mobile-readable phrases, strong contrast, and platform-safe placement.",
        "One concise phrase per readable beat",
        cues=("caption", "subtitle", "text"),
    ),
    _pattern(
        "minimal_clutter",
        "caption",
        "Minimal caption clutter",
        "Keep the frame clear when facial expression or performance carries the moment.",
        "Sparse captions on only essential lines",
        cues=("clean", "minimal", "performance"),
        niches=("music_singing", "emotional_story", "podcast_interview"),
    ),
    _pattern(
        "fast_reaction_captions",
        "caption",
        "Fast reaction captions",
        "Use brief energetic phrases on genuine reaction beats without covering gameplay.",
        "Reaction word -> event label -> payoff phrase",
        cues=("reaction", "no way", "what"),
        niches=("gaming_stream", "reaction", "sports"),
    ),
    _pattern(
        "tight_clarity",
        "pacing",
        "Tight clarity-first pacing",
        "Remove repetition while preserving setup, reasoning, and payoff.",
        "Hook -> necessary context -> complete answer",
        cues=("because", "example", "therefore", "lesson"),
    ),
    _pattern(
        "fast_pattern_interrupts",
        "pacing",
        "Fast controlled pattern interrupts",
        "Use visual changes at meaningful beats rather than constant random motion.",
        "Hook change -> event beat -> payoff emphasis",
        cues=("suddenly", "then", "watch", "reaction"),
        niches=("gaming_stream", "reaction", "entertainment_comedy", "sports"),
    ),
    _pattern(
        "restrained_emotional_pacing",
        "pacing",
        "Restrained emotional pacing",
        "Let emotional turns breathe while removing unrelated pauses.",
        "Confession -> quiet turn -> landing",
        cues=("i felt", "realized", "moment", "changed"),
        niches=("motivational", "emotional_story", "relationship_life_advice"),
    ),
    _pattern(
        "hook_punch_in",
        "editing",
        "Hook punch-in",
        "Use one clean opening punch-in tied to the first meaningful word.",
        "Cold open -> brief punch-in -> stable framing",
        cues=("hook", "first", "open"),
    ),
    _pattern(
        "active_speaker_focus",
        "editing",
        "Active-speaker focus",
        "Keep the speaking face clearly framed and avoid decorative switching.",
        "Stable speaker frame -> deliberate switch on speaker change",
        cues=("speaker", "interview", "conversation"),
        niches=("podcast_interview", "debate_argument", "reaction"),
    ),
    _pattern(
        "payoff_hold",
        "editing",
        "Payoff hold",
        "Hold the final caption or frame briefly so the payoff is not clipped.",
        "Payoff line -> short readable tail",
        cues=("payoff", "finally", "lesson", "answer"),
    ),
    _pattern(
        "clean_transitions",
        "editing",
        "Clean transitions",
        "Prefer motivated cuts and subtle motion over template-heavy effects.",
        "Beat-aligned cut -> stable next composition",
        cues=("then", "next", "changed", "cut"),
    ),
    _pattern(
        "reaction_emphasis",
        "editing",
        "Reaction emphasis",
        "Emphasize the real reaction with framing or a brief zoom, not fabricated audio.",
        "Event -> authentic reaction -> replay beat",
        cues=("reaction", "no way", "look"),
        niches=("reaction", "gaming_stream", "sports", "entertainment_comedy"),
    ),
    _pattern(
        "subtle_speech_bed",
        "music",
        "Subtle speech-first music bed",
        "Match mood while keeping dialogue clearly dominant.",
        "Low music bed -> gentle payoff lift -> fade",
        cues=("speech", "conversation", "lesson"),
        safety_notes="Music must remain audible but clearly below the voice.",
    ),
    _pattern(
        "emotional_swell",
        "music",
        "Conservative emotional swell",
        "Use a small musical lift near a real emotional turn or payoff.",
        "Subtle bed -> restrained swell -> clean fade",
        cues=("emotional", "realized", "changed", "payoff"),
        niches=("motivational", "emotional_story", "relationship_life_advice"),
        safety_notes="Never overpower speech or manufacture emotion unsupported by the clip.",
    ),
    _pattern(
        "audio_clarity_priority",
        "music",
        "Audio clarity priority",
        "Preserve performance vocals and avoid competing SFX or music overlays.",
        "Clean source vocal -> minimal supporting audio",
        cues=("sing", "song", "vocal", "performance"),
        niches=("music_singing",),
        safety_notes="Do not add music under music; preserve the source performance.",
    ),
    _pattern(
        "energetic_clean_bed",
        "music",
        "Energetic clean bed",
        "Use a controlled energetic bed only when it leaves commentary intelligible.",
        "Low energetic bed -> event accent -> fade",
        cues=("game", "reaction", "win", "goal"),
        niches=("gaming_stream", "reaction", "sports", "entertainment_comedy"),
    ),
    _pattern(
        "curiosity_without_lying",
        "title",
        "Curiosity without lying",
        "Frame the real unresolved question without inventing a larger promise.",
        "Why/How + specific source-backed subject",
        cues=("why", "how", "reason"),
    ),
    _pattern(
        "specific_outcome",
        "title",
        "Specific outcome framing",
        "Name the real result or lesson rather than using vague hype.",
        "Specific result + relevant context",
        cues=("result", "learned", "fixed", "changed"),
    ),
    _pattern(
        "mistake_framing",
        "title",
        "Mistake framing",
        "Name the source-backed mistake and its relevant consequence.",
        "The mistake behind + real topic",
        cues=("mistake", "wrong", "avoid"),
    ),
    _pattern(
        "identity_target",
        "title",
        "Relevant identity framing",
        "Address the real audience without exclusionary or manipulative claims.",
        "For + relevant audience + specific lesson",
        cues=("for creators", "for beginners", "if you're"),
    ),
    _pattern(
        "limited_niche_tags",
        "hashtag",
        "Limited niche hashtags",
        "Use a small set of relevant niche and platform tags; avoid spam clouds.",
        "Platform tag + two or three specific niche tags",
        cues=("shorts", "reels", "tiktok"),
    ),
    _pattern(
        "avoid_filler",
        "risk",
        "Avoid filler before payoff",
        "Do not let trend styling justify dead air, repetition, or missing payoff.",
        "Complete story first; trend treatment second",
        cues=("um", "you know", "basically", "repeating"),
        confidence=0.82,
    ),
    _pattern(
        "avoid_overpowering_audio",
        "risk",
        "Avoid overpowering audio",
        "Music and clean SFX must support, never mask, the source voice or performance.",
        "Speech-first mix with conservative accents",
        cues=("music", "sound", "voice", "audio"),
        confidence=0.86,
    ),
    _pattern(
        "avoid_copying_trend_expression",
        "risk",
        "Do not copy trend expression",
        "Reuse only high-level structure, never another creator's protected expression.",
        "Original source material + general structural guidance",
        cues=("viral", "trend", "creator"),
        confidence=0.95,
        safety_notes=DO_NOT_COPY_WARNING,
    ),
)

PATTERN_LIBRARY: dict[str, dict[str, Any]] = {
    str(pattern["pattern_id"]): pattern for pattern in _PATTERNS
}

COMMON_PATTERN_IDS = (
    "question_hook",
    "problem_solution",
    "fast_first_sentence",
    "quick_context",
    "satisfying_answer",
    "short_high_contrast",
    "tight_clarity",
    "hook_punch_in",
    "clean_transitions",
    "subtle_speech_bed",
    "curiosity_without_lying",
    "limited_niche_tags",
    "avoid_filler",
    "avoid_overpowering_audio",
    "avoid_copying_trend_expression",
)

NICHE_PATTERN_IDS: dict[str, tuple[str, ...]] = {
    "podcast_interview": (
        "contrarian_truth",
        "emotional_confession",
        "question_answer",
        "conflict_resolution",
        "confession_meaning",
        "active_speaker_focus",
        "minimal_clutter",
        "strong_quote",
    ),
    "motivational": (
        "identity_hook",
        "before_after_hook",
        "pain_transformation",
        "restrained_emotional_pacing",
        "emotional_landing",
        "strong_quote",
        "bold_keywords",
        "emotional_swell",
        "payoff_hold",
    ),
    "business_money": (
        "contrarian_truth",
        "mistake_warning",
        "mistake_lesson",
        "practical_takeaway",
        "specific_outcome",
        "mistake_framing",
        "bold_keywords",
    ),
    "self_improvement": (
        "identity_hook",
        "mistake_warning",
        "before_after_hook",
        "pain_transformation",
        "practical_takeaway",
        "bold_keywords",
        "payoff_hold",
    ),
    "education_tutorial": (
        "mistake_warning",
        "question_answer",
        "mistake_lesson",
        "practical_takeaway",
        "bold_keywords",
        "specific_outcome",
        "mistake_framing",
        "payoff_hold",
    ),
    "entertainment_comedy": (
        "immediate_reaction",
        "fast_setup_punchline",
        "buildup_payoff",
        "punchline",
        "fast_pattern_interrupts",
        "reaction_emphasis",
        "energetic_clean_bed",
    ),
    "gaming_stream": (
        "immediate_reaction",
        "reaction_explanation",
        "buildup_payoff",
        "replay_worthy_moment",
        "fast_reaction_captions",
        "fast_pattern_interrupts",
        "reaction_emphasis",
        "energetic_clean_bed",
    ),
    "reaction": (
        "immediate_reaction",
        "reaction_explanation",
        "replay_worthy_moment",
        "fast_reaction_captions",
        "fast_pattern_interrupts",
        "reaction_emphasis",
    ),
    "music_singing": (
        "payoff_first",
        "buildup_payoff",
        "replay_worthy_moment",
        "emotional_landing",
        "minimal_clutter",
        "audio_clarity_priority",
        "payoff_hold",
    ),
    "sports": (
        "immediate_reaction",
        "before_after_hook",
        "buildup_payoff",
        "replay_worthy_moment",
        "fast_reaction_captions",
        "reaction_emphasis",
        "energetic_clean_bed",
    ),
    "emotional_story": (
        "emotional_confession",
        "confession_meaning",
        "pain_transformation",
        "restrained_emotional_pacing",
        "emotional_landing",
        "minimal_clutter",
        "emotional_swell",
        "payoff_hold",
    ),
    "news_commentary": (
        "question_hook",
        "contrarian_truth",
        "question_answer",
        "conflict_resolution",
        "practical_takeaway",
        "active_speaker_focus",
    ),
    "debate_argument": (
        "contrarian_truth",
        "high_stakes_hook",
        "conflict_resolution",
        "question_answer",
        "strong_quote",
        "active_speaker_focus",
    ),
    "fitness": (
        "mistake_warning",
        "identity_hook",
        "before_after_hook",
        "pain_transformation",
        "practical_takeaway",
        "bold_keywords",
    ),
    "relationship_life_advice": (
        "emotional_confession",
        "identity_hook",
        "confession_meaning",
        "conflict_resolution",
        "practical_takeaway",
        "emotional_landing",
    ),
    "tech_ai": (
        "question_hook",
        "mistake_warning",
        "problem_solution",
        "question_answer",
        "practical_takeaway",
        "bold_keywords",
        "specific_outcome",
    ),
    "unknown_mixed": (),
}


def patterns_for_niche(niche: str) -> list[dict[str, Any]]:
    """Return independent JSON-safe pattern objects for one niche."""

    canonical = normalize_niche(niche)
    identifiers = dict.fromkeys((*COMMON_PATTERN_IDS, *NICHE_PATTERN_IDS[canonical]))
    patterns: list[dict[str, Any]] = []
    for pattern_id in identifiers:
        source = PATTERN_LIBRARY[pattern_id]
        copy = dict(source)
        for field in (
            "applies_to_niches",
            "platforms",
            "evidence_source_ids",
            "match_cues",
            "cues",
        ):
            copy[field] = list(source[field])
        patterns.append(copy)
    return patterns


def pattern_by_id(pattern_id: str) -> dict[str, Any] | None:
    """Return an independent pattern object by id."""

    pattern = PATTERN_LIBRARY.get(pattern_id)
    if pattern is None:
        return None
    copy = dict(pattern)
    for field in (
        "applies_to_niches",
        "platforms",
        "evidence_source_ids",
        "match_cues",
        "cues",
    ):
        copy[field] = list(pattern[field])
    return copy


def patterns_by_category(patterns: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    """Group pattern objects into the public snapshot category fields."""

    grouped: dict[str, list[dict[str, Any]]] = {
        "hook": [],
        "storytelling": [],
        "retention": [],
        "ending": [],
        "caption": [],
        "pacing": [],
        "music": [],
        "editing": [],
        "title": [],
        "hashtag": [],
        "risk": [],
    }
    for pattern in patterns:
        category = str(pattern.get("category") or "")
        if category in grouped:
            grouped[category].append(pattern)
    return grouped
